web: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
worker: celery -A core worker --loglevel=info --pool=solo
beat: celery -A core beat --loglevel=info
release: python manage.py migrate && python seed.py